CREATE DATABASE /*!32312 IF NOT EXISTS*/ `sample` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `sample`;

CREATE USER 'app'@'%' IDENTIFIED BY 'qwerty';
GRANT ALL PRIVILEGES ON sample.* TO 'app'@'%' WITH GRANT OPTION;
